server:
  port: 8888
spring:
  application:
    name: web
  cloud:
    nacos:
      discovery:
        server-addr: 62.4.22.8:8848
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    favicon:
      enabled: false