server:
  port: 666
spring:
  application:
    name: web

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    favicon:
      enabled: false
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181