server:
  port: 8764
spring:
  application:
    name: torrent-store-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
      bindings:
        torrent-message-in:
          group: torrent-store-group
          destination: torrentMessages
          contentType: application/json
          consumer:
            compressionType: gzip
            autoCommitOffset: false #设置手动提交偏移
        index-message-in:
          group: torrent-index-group
          destination: torrentMessages
          contentType: application/json
          consumer:
            compressionType: gzip
            autoCommitOffset: false #设置手动提交偏移
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
#  main:
#    allow-bean-definition-overriding: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: cc.dodder.torrent.store.api.impl
logging:
  level:
    root: info