server:
  port: 8764
spring:
  application:
    name: torrent-store-service
  cloud:
    nacos:
      discovery:
        server-addr: 62.4.22.8:8848
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9200
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录

management:
  endpoints:
    web:
      exposure:
        include: ["*"]